ProjectReviewBuku/routes/web.php
<?php

// routes/web.php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenulisController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PenerbitController;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\RegistrasiController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/profile', function () {
    return view('partial.profile');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/profiles', [ProfileController::class, 'index'])->name('profiles.index');
    Route::get('/profiles/create', [ProfileController::class, 'create'])->name('profiles.create');
    Route::post('/profiles', [ProfileController::class, 'store'])->name('profiles.store');
    Route::get('/profiles/show', [ProfileController::class, 'show'])->name('profiles.show');
    Route::get('/profiles/edit', [ProfileController::class, 'edit'])->name('profiles.edit');
    Route::post('/profiles/update', [ProfileController::class, 'update'])->name('profiles.update');
    Route::delete('/profiles/destroy', [ProfileController::class, 'destroy'])->name('profiles.destroy');
});

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('penulis', PenulisController::class);
Route::resource('genre', GenreController::class);
Route::resource('penerbit', PenerbitController::class);
Route::resource('profiles', ProfileController::class);
Route::resource('buku', BukuController::class);
Route::resource('reviews', ReviewController::class);


// Registration Routes
Route::get('/register', [RegistrasiController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [RegistrasiController::class, 'register']);

// Login Routes
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

ProjectReviewBuku/app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use App\Models\Review;
use App\Models\User;
use App\Models\Buku;
use Illuminate\Http\Request;

class ReviewController extends Controller
{
    public function index()
    {
        $reviews = Review::with(['user', 'buku'])->get();
        return view('reviews.index', compact('reviews'));
    }

    public function create()
    {
        $users = User::all();
        $bukus = Buku::all();
        return view('reviews.create', compact('users', 'bukus'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'ulasan' => 'required',
            'rating' => 'required|integer',
            'pendapat' => 'nullable',
            'user_id' => 'required|exists:users,id',
            'buku_id' => 'required|exists:buku,id',
        ]);

        Review::create($request->all());
        return redirect()->route('reviews.index')->with('success', 'Review created successfully.');
    }

    public function show(Review $review)
    {
        return view('reviews.show', compact('review'));
    }

    public function edit(Review $review)
    {
        $users = User::all();
        $bukus = Buku::all();
        return view('reviews.edit', compact('review', 'users', 'bukus'));
    }

    public function update(Request $request, Review $review)
    {
        $request->validate([
            'ulasan' => 'required',
            'rating' => 'required|integer',
            'pendapat' => 'nullable',
            'user_id' => 'required|exists:users,id',
            'buku_id' => 'required|exists:buku,id',
        ]);

        $review->update($request->all());
        return redirect()->route('reviews.index')->with('success', 'Review updated successfully.');
    }

    public function destroy(Review $review)
    {
        $review->delete();
        return redirect()->route('reviews.index')->with('success', 'Review deleted successfully.');
    }
}

ProjectReviewBuku/resources/views/reviews/create.blade.php
@extends('layout.master')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2 class="text-center mb-4">Tambah Review</h2>
                <form action="{{ route('reviews.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="ulasan">Ulasan</label>
                        <textarea class="form-control" id="ulasan" name="ulasan" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="rating">Rating</label>
                        <input type="number" class="form-control" id="rating" name="rating" required>
                    </div>
                    <div class="form-group">
                        <label for="pendapat">Pendapat</label>
                        <textarea class="form-control" id="pendapat" name="pendapat"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="user_id">User</label>
                        <select class="form-control" id="user_id" name="user_id" required>
                            @foreach ($users as $user)
                                <option value="{{ $user->id }}">{{ $user->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="buku_id">Buku</label>
                        <select class="form-control" id="buku_id" name="buku_id" required>
                            @foreach ($bukus as $buku)
                                <option value="{{ $buku->id }}">{{ $buku->judul }}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Simpan</button>
                </form>
            </div>
        </div>
    </div>
@endsection

ProjectReviewBuku/resources/views/reviews/edit.blade.php
@extends('layout.master')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2 class="text-center mb-4">Edit Review</h2>
                <form action="{{ route('reviews.update', $review->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="ulasan">Ulasan</label>
                        <textarea class="form-control" id="ulasan" name="ulasan" required>{{ $review->ulasan }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="rating">Rating</label>
                        <input type="number" class="form-control" id="rating" name="rating" value="{{ $review->rating }}" required>
                    </div>
                    <div class="form-group">
                        <label for="pendapat">Pendapat</label>
                        <textarea class="form-control" id="pendapat" name="pendapat">{{ $review->pendapat }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="user_id">User</label>
                        <select class="form-control" id="user_id" name="user_id" required>
                            @foreach ($users as $user)
                                <option value="{{ $user->id }}" {{ $user->id == $review->user_id ? 'selected' : '' }}>{{ $user->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="buku_id">Buku</label>
                        <select class="form-control" id="buku_id" name="buku_id" required>
                            @foreach ($bukus as $buku)
                                <option value="{{ $buku->id }}" {{ $buku->id == $review->buku_id ? 'selected' : '' }}>{{ $buku->judul }}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Simpan</button>
                </form>
            </div>
        </div>
    </div>
@endsection

ProjectReviewBuku/resources/views/reviews/index.blade.php
@extends('layout.master')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <h2 class="text-center mb-4">Daftar Review</h2>
                <a href="{{ route('reviews.create') }}" class="btn btn-success mb-3">Tambah Review</a>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Ulasan</th>
                                <th class="text-center">Rating</th>
                                <th class="text-center">Pendapat</th>
                                <th class="text-center">User</th>
                                <th class="text-center">Buku</th>
                                <th class="text-center" width="280px">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($reviews as $key => $review)
                                <tr>
                                    <td class="text-center">{{ $key + 1 }}</td>
                                    <td>{{ $review->ulasan }}</td>
                                    <td class="text-center">{{ $review->rating }}</td>
                                    <td>{{ $review->pendapat }}</td>
                                    <td class="text-center">{{ $review->user->name }}</td>
                                    <td class="text-center">{{ $review->buku->judul }}</td>
                                    <td class="text-center">
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a class="btn btn-info btn-sm" href="{{ route('reviews.show', $review->id) }}">Show</a>
                                            <a class="btn btn-primary btn-sm" href="{{ route('reviews.edit', $review->id) }}">Edit</a>
                                            <form action="{{ route('reviews.destroy', $review->id) }}" method="POST" style="display:inline;">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-center">Daftar review tidak tersedia</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

ProjectReviewBuku/resources/views/reviews/show.blade.php
@extends('layout.master')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2 class="text-center mb-4">Detail Review</h2>
                <div class="card">
                    <div class="card-header">
                        Review ID: {{ $review->id }}
                    </div>
                    <div class="card-body">
                        <p><strong>Ulasan:</strong> {{ $review->ulasan }}</p>
                        <p><strong>Rating:</strong> {{ $review->rating }}</p>
                        <p><strong>Pendapat:</strong> {{ $review->pendapat }}</p>
                        <p><strong>Username:</strong> {{ $review->user->name }}</p>
                        <p><strong>Judul Buku:</strong> {{ $review->buku->judul }}</p>
                        <a href="{{ route('reviews.index') }}" class="btn btn-secondary">Kembali</a>
                        <a href="{{ route('reviews.edit', $review->id) }}" class="btn btn-primary">Edit</a>
                        <form action="{{ route('reviews.destroy', $review->id) }}" method="POST" style="display:inline;">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection