ProjectReviewBuku/routes/web.php
<?php

// routes/web.php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenulisController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PenerbitController;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\RegistrasiController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/profile', function () {
    return view('partial.profile');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/profiles', [ProfileController::class, 'index'])->name('profiles.index');
    Route::get('/profiles/create', [ProfileController::class, 'create'])->name('profiles.create');
    Route::post('/profiles', [ProfileController::class, 'store'])->name('profiles.store');
    Route::get('/profiles/show', [ProfileController::class, 'show'])->name('profiles.show');
    Route::get('/profiles/edit', [ProfileController::class, 'edit'])->name('profiles.edit');
    Route::post('/profiles/update', [ProfileController::class, 'update'])->name('profiles.update');
    Route::delete('/profiles/destroy', [ProfileController::class, 'destroy'])->name('profiles.destroy');
});

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('penulis', PenulisController::class);
Route::resource('genre', GenreController::class);
Route::resource('penerbit', PenerbitController::class);
Route::resource('profiles', ProfileController::class);
Route::resource('buku', BukuController::class);
Route::resource('reviews', ReviewController::class);


// Registration Routes
Route::get('/register', [RegistrasiController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [RegistrasiController::class, 'register']);

// Login Routes
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

ProjectReviewBuku/resources/views/partial/header.blade.php
<!-- Header Start -->
<header>
    <div class="header-area">
        <div class="main-header header-sticky">
            <div class="container-fluid">
                <div class="menu-wrapper">
                    <!-- Logo -->
                    <div class="logo">
                        <a href="index.html"><img src="{{ asset('/Template/assets/img/ebook/ebook.png') }}" width="90"
                                height="80"></a>
                    </div>
                    <!-- Main-menu -->
                    <div class="main-menu d-none d-lg-block">
                        <nav>
                            <ul id="navigation">
                                <li><a href="{{ route('home') }}">Home</a></li>
                                <li><a href="{{ route('buku.index') }}">Buku</a></li>
                                <li><a href="/genre">Genre</a></li>
                                <li><a href="{{ route('reviews.index') }}">Review</a></li>
                                <li><a href="/penulis">Penulis</a></li>
                                <li><a href="/penerbit">Penerbit</a></li>
                                @auth
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                        style="display: none;">
                                        @csrf
                                    </form>
                                    <li>
                                        <a href="#"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                                    </li>
                                @else
                                    <li>
                                        <a href="{{ route('login') }}">Login</a>
                                    </li>
                                @endauth
                            </ul>
                        </nav>
                    </div>
                    <!-- Header Right -->
                    <div class="header-right">
                        <ul>
                            <li><a href="{{ route ('profiles.index')}}">Profile</a></li>
                            <li>
                                <a class="nav-link" href="{{ route('profiles.index') }}"><span class="flaticon-user"></span>Profile</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Header End -->

ProjectReviewBuku/resources/views/partial/home.blade.php
@extends('layout.master')
@section('content')
    <!-- Single Slider -->
    <div class="single-slider slider-height d-flex align-items-center slide-bg">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8">
                    <div class="hero__caption">
                        <h1 data-animation="fadeInLeft" data-delay=".4s" data-duration="2000ms">Review Buku</h1>
                        <p data-animation="fadeInLeft" data-delay=".7s" data-duration="2000ms">"Apakah Anda seorang pecinta
                            buku yang selalu haus akan cerita-cerita baru dan inspiratif? Di sini, kami menyajikan ulasan
                            mendalam tentang berbagai genre buku yang pastinya akan menambah daftar bacaan Anda. Mari
                            jelajahi dunia literasi bersama!"</p>
                        <!-- Hero-btn -->
                        <div class="hero__btn" data-animation="fadeInLeft" data-delay=".8s" data-duration="2000ms">
                            <a href="{{ route('register') }}" class="btn hero-btn">Registrasi sekarang</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4 d-none d-sm-block">
                    <div class="hero__img" data-animation="bounceIn" data-delay=".3s">
                        <img src="{{ asset('/Template/assets/img/ebook/ebook_content1.jpg') }}" width="380"
                            height="400" class=" heartbeat">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Single Slider -->
    <div class="single-slider slider-height d-flex align-items-center slide-bg">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8">
                    <div class="hero__caption">
                        <h1 data-animation="fadeInLeft" data-delay=".4s" data-duration="2000ms">Selamat Datang di Dunia
                            Literasi!</h1>
                        <p data-animation="fadeInLeft" data-delay=".7s" data-duration="2000ms">"Di sini, kami percaya bahwa
                            setiap buku memiliki pembacanya. Temukan ulasan-ulasan yang jujur, mendalam, dan penuh wawasan
                            untuk membantu Anda menemukan buku berikutnya yang akan Anda cintai."</p>
                        <!-- Hero-btn -->
                        <div class="hero__btn" data-animation="fadeInLeft" data-delay=".8s" data-duration="2000ms">
                            <a href="industries.html" class="btn hero-btn">Registrasi sekarang</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4 d-none d-sm-block">
                    <div class="hero__img" data-animation="bounceIn" data-delay=".es">
                        <img src="{{ asset('/Template/assets/img/ebook/ebook_content1.jpg') }}" width="380"
                            height="400" class=" heartbeat">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

ProjectReviewBuku/resources/views/partial/profile.blade.php
@extends('layout.master')

@section('content')
<<<<<<< Updated upstream
=======

>>>>>>> Stashed changes
    <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Profil Pengguna</div>
                        <div class="card-body">
                            <div class="mb-3">
                                {{-- <a href="{{ route('profile.edit') }}" class="btn btn-primary">Edit Profile</a> --}}
                            </div>
                            <form method="POST"
                                action="{{ isset($profil) ? route('profile.update') : route('profile.store') }}">
                                @csrf
                                @if (isset($profil))
                                    @method('PUT')
                                @endif
                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
                                    <div class="col-md-6">
                                        <input id="email" type="email" class="form-control" name="email"
                                            value="{{ Auth::user()->email }}" disabled>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                                    <div class="col-md-6">
                                        <input id="name" type="text" class="form-control" name="name"
                                            value="{{ Auth::user()->name }}" disabled>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="umur" class="col-md-4 col-form-label text-md-right">Umur</label>
                                    <div class="col-md-6">
                                        <input id="umur" type="number" class="form-control" name="umur"
                                            value="{{ $profil->umur ?? '' }}" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="alamat" class="col-md-4 col-form-label text-md-right">Alamat</label>
                                    <div class="col-md-6">
                                        <input id="alamat" type="text" class="form-control" name="alamat"
                                            value="{{ $profil->alamat ?? '' }}" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="bio" class="col-md-4 col-form-label text-md-right">Bio</label>
                                    <div class="col-md-6">
                                        <textarea id="bio" class="form-control" name="bio" rows="3">{{ $profil->bio ?? '' }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ isset($profil) ? 'Update' : 'Add' }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
<<<<<<< Updated upstream
                    <div class="form-group">
                        <label>Username</label>
                        <br>
                        <input type="text" class="form-control" placeholder="username">
                    </div>
                    <div class="form-group">
                        <label>Umur</label>
                        <br>
                        <input type="integer" class="form-control" placeholder="umur">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Bio</label>
                        <textarea class="form-control" rows="3"></textarea>
                    </div>
                    <button type="button" class="btn btn-success">Simpan</button>
                </form>
            </div>
        </div>
    </body>
@endsection
=======

                    <body>
                        <div class="form-wrapper">
                            <div class="container">
                                <form>
                                    @csrf
                                    <div class="form-group">
                                        <label>Email address</label>
                                        <br>
                                        <input type="text" class="form-control" placeholder="email">
                                    </div>
                                    <div class="form-group">
                                        <label>Username</label>
                                        <br>
                                        <input type="text" class="form-control" placeholder="username">
                                    </div>
                                    <div class="form-group">
                                        <label>Umur</label>
                                        <br>
                                        <input type="integer" class="form-control" placeholder="umur">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Bio</label>
                                        <textarea class="form-control" rows="3"></textarea>
                                    </div>
                                    <button type="button" class="btn btn-success">Simpan</button>
                                </form>
                            </div>
                        </div>
                    </body>
                @endsection
>>>>>>> Stashed changes