ProjectReviewBuku/routes/web.php
<?php

// routes/web.php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenulisController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PenerbitController;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\RegistrasiController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/profile', function () {
    return view('partial.profile');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/profiles', [ProfileController::class, 'index'])->name('profiles.index');
    Route::get('/profiles/create', [ProfileController::class, 'create'])->name('profiles.create');
    Route::post('/profiles', [ProfileController::class, 'store'])->name('profiles.store');
    Route::get('/profiles/show', [ProfileController::class, 'show'])->name('profiles.show');
    Route::get('/profiles/edit', [ProfileController::class, 'edit'])->name('profiles.edit');
    Route::post('/profiles/update', [ProfileController::class, 'update'])->name('profiles.update');
    Route::delete('/profiles/destroy', [ProfileController::class, 'destroy'])->name('profiles.destroy');
});

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('penulis', PenulisController::class);
Route::resource('genre', GenreController::class);
Route::resource('penerbit', PenerbitController::class);
Route::resource('profiles', ProfileController::class);
Route::resource('buku', BukuController::class);
Route::resource('reviews', ReviewController::class);


// Registration Routes
Route::get('/register', [RegistrasiController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [RegistrasiController::class, 'register']);

// Login Routes
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

ProjectReviewBuku/app/Models/Penerbit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Penerbit extends Model
{
    use HasFactory;
    protected $table = 'penerbit';
    protected $fillable = ['nama' , 'alamat', 'telepon', 'email', 'website'];
}

ProjectReviewBuku/app/Http/Controllers/PenerbitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Penerbit;

class PenerbitController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $penerbit = Penerbit::all();
        return view('penerbit.view', ['penerbit' => $penerbit]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('penerbit.tambah');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'nama' => 'required|min:4',
                'alamat' => 'required',
                'telepon' => 'required',
                'email' => 'required',
                'website' => 'required',
            ],
            [
                'nama.required' => 'Isilah Nama Anda!',
                'alamat.required' => 'Alamat Harus Diisi!',
                'telepon.required' => 'No Telepon Harus Diisi',
                'email.required' => 'Tulislah alamat email Anda!',
                'website.required' => 'Isi halaman website anda!',
            ]
        );

        $penerbit = new Penerbit;
        $penerbit->nama = $request->input('nama');
        $penerbit->alamat = $request->input('alamat');
        $penerbit->telepon = $request->input('telepon');
        $penerbit->email = $request->input('email');
        $penerbit->website = $request->input('website');
        $penerbit->save();

        return redirect('/penerbit');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $penerbit = Penerbit::find($id);
        return view('penerbit.detail', ['penerbit' => $penerbit]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $penerbit = Penerbit::findOrFail($id);
        return view('penerbit.edit', compact('penerbit'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'nama' => 'required|min:4',
            'alamat' => 'required',
            'telepon' => 'required',
            'email' => 'required',
            'website' => 'required',
        ]);

        // Temukan data penerbit berdasarkan ID
        $penerbit = Penerbit::findOrFail($id);

        // Simpan perubahan data yang diterima dari formulir
        $penerbit->nama = $request->nama;
        $penerbit->alamat = $request->alamat;
        $penerbit->telepon = $request->telepon;
        $penerbit->email = $request->email;
        $penerbit->website = $request->website;
        $penerbit->save();

        return redirect('/penerbit');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $penerbit = Penerbit::findOrFail($id);
        $penerbit->delete();

        return redirect('/penerbit');
    }
}

ProjectReviewBuku/resources/views/penerbit/detail.blade.php
@extends('layout.master')

@section('title', 'Halaman Detail Penerbit')

@section('content')
    <div class="container-fluid"> <!-- Container-fluid untuk mengisi seluruh lebar halaman -->
        <div class="row justify-content-center"> <!-- Row justify-content-center untuk mengatur posisi ke tengah -->
            <div class="col-md-8"> <!-- Mengurangi lebar konten agar tidak terlalu lebar -->
                <h3 class="text-left mb-4" style="font-size: 1.5em;">Halaman Detail Penerbit</h3>
                <h1 class="text-center mb-4">{{ $penerbit->nama }}</h1>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr>
                            <th style="width: 30%;">Alamat</th>
                            <td>{{ $penerbit->alamat }}</td>
                        </tr>
                        <tr>
                            <th>Telepon</th>
                            <td>{{ $penerbit->telepon }}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ $penerbit->email }}</td>
                        </tr>
                        <tr>
                            <th>Website</th>
                            <td>{{ $penerbit->website }}</td>
                        </tr>
                    </table>
                </div>
                <a href="{{ url('/penerbit') }}" class="btn btn-primary mt-3">Kembali</a>
            </div>
        </div>
    </div>
@endsection

ProjectReviewBuku/resources/views/penerbit/edit.blade.php
@extends('layout.master')
@section('title', 'Halaman Edit Penerbit')
@section('content')

    <div class="form-wrapper">
        <div class="container">
            <form method="post" action="{{ route('penerbit.update', $penerbit->id) }}">
                @csrf
                @method('PUT')
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-group">
                    <label for="nama">Nama</label>
                    <input type="text" id="nama" name="nama" class="form-control" value="{{ $penerbit->nama }}">
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <input type="text" id="alamat" name="alamat" class="form-control"
                        value="{{ $penerbit->alamat }}">
                </div>
                <div class="form-group">
                    <label for="telepon">Telepon</label>
                    <input type="text" id="telepon" name="telepon" class="form-control"
                        value="{{ $penerbit->telepon }}">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" class="form-control" value="{{ $penerbit->email }}">
                </div>
                <div class="form-group">
                    <label for="website">Website</label>
                    <input type="text" id="website" name="website" class="form-control"
                        value="{{ $penerbit->website }}">
                </div>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
    </div>

@endsection

ProjectReviewBuku/resources/views/penerbit/tambah.blade.php
@extends('layout.master')
@section('title', 'Halaman Tambah Penerbit')
@section('content')

    <div class="form-wrapper">
        <div class="container">
            <form method="post" action="/penerbit">
                @csrf
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-group">
                    <label for="nama">Nama</label>
                    <input type="varchar" id="nama" name="nama" class="form-control">
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <input type="varchar" id="alamat" name="alamat" class="form-control">
                </div>
                <div class="form-group">
                    <label for="">Telepon</label>
                    <input type="integer" id="telepon" name="telepon" class="form-control">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <textarea id="varchar" name="email" class="form-control" rows="3"></textarea>
                </div>
                <div class="form-group">
                    <label for="website">Website</label>
                    <input type="varchar" id="website" name="website" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
    </div>

@endsection

ProjectReviewBuku/resources/views/penerbit/view.blade.php
@extends('layout.master')

@section('title', 'Halaman Tampilan Penerbit')

@section('content')
    <div class="container-fluid"> <!-- Container-fluid untuk mengisi seluruh lebar halaman -->
        <div class="row justify-content-center"> <!-- Row justify-content-center untuk mengatur posisi ke tengah -->
            <div class="col-md-10"> <!-- Mengurangi lebar konten agar tidak terlalu lebar -->
                <h2 class="text-center mb-4">Daftar Penerbit</h2>
                <a href="{{ url('/penerbit/create') }}" class="btn btn-success mb-3">Tambah Penerbit</a>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th class="text-center">ID</th>
                                <th class="text-center">Nama</th>
                                <th class="text-center">Alamat</th>
                                <th class="text-center">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($penerbit as $penerbitItem)
                                <tr>
                                    <td class="text-center">{{ $penerbitItem->id }}</td>
                                    <td class="text-center">{{ $penerbitItem->nama }}</td>
                                    <td class="text-center">{{ $penerbitItem->alamat }}</td>
                                    <td class="text-center">
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a href="{{ url('/penerbit/' . $penerbitItem->id . '/edit') }}"
                                                class="btn btn-warning btn-sm mr-2">Edit</a>
                                            <a href="{{ url('/penerbit/' . $penerbitItem->id) }}"
                                                class="btn btn-info btn-sm">Detail</a>

                                        </div>
                                    </td>
                                </tr>

                            @empty
                                <tr>
                                    <td colspan="7" class="text-center">Daftar penerbit tidak tersedia</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <a href="{{ route ('home')}}" class="btn btn-primary mt-3">Kembali</a>
            </div>
        </div>
    </div>
@endsection