ProjectReviewBuku/routes/web.php
<?php

// routes/web.php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenulisController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PenerbitController;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\RegistrasiController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/profile', function () {
    return view('partial.profile');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/profiles', [ProfileController::class, 'index'])->name('profiles.index');
    Route::get('/profiles/create', [ProfileController::class, 'create'])->name('profiles.create');
    Route::post('/profiles', [ProfileController::class, 'store'])->name('profiles.store');
    Route::get('/profiles/show', [ProfileController::class, 'show'])->name('profiles.show');
    Route::get('/profiles/edit', [ProfileController::class, 'edit'])->name('profiles.edit');
    Route::post('/profiles/update', [ProfileController::class, 'update'])->name('profiles.update');
    Route::delete('/profiles/destroy', [ProfileController::class, 'destroy'])->name('profiles.destroy');
});

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('penulis', PenulisController::class);
Route::resource('genre', GenreController::class);
Route::resource('penerbit', PenerbitController::class);
Route::resource('profiles', ProfileController::class);
Route::resource('buku', BukuController::class);
Route::resource('reviews', ReviewController::class);


// Registration Routes
Route::get('/register', [RegistrasiController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [RegistrasiController::class, 'register']);

// Login Routes
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

ProjectReviewBuku/app/Models/Buku.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    use HasFactory;
    protected $table = 'buku';
    protected $fillable = ['judul', 'sinopsis', 'tahun_penerbitan', 'genre_id', 'penulis_id', 'penerbit_id'];

    // Definisikan relasi dengan model Genre
    public function genre()
    {
        return $this->belongsTo(Genre::class);
    }
    public function penulis()
    {
        return $this->belongsTo(Penulis::class);
    }
    public function penerbit()
    {
        return $this->belongsTo(Penerbit::class);
    }
    public function reviews()
    {
        return $this->hasMany(Review::class);
    }
}

ProjectReviewBuku/app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use App\Models\Buku;
use App\Models\Genre;
use App\Models\Penulis;
use App\Models\Penerbit;
use Illuminate\Http\Request;

class BukuController extends Controller
{
    public function index()
    {
        $buku = Buku::all();
        return view('buku.index', compact('buku'));
    }

    public function create()
    {
        $genre = Genre::all(); // Mengambil semua genre dari database
        $penulis = Penulis::all(); // Mengambil semua penulis dari database
        $penerbit = Penerbit::all(); // Mengambil semua penerbit dari database
        // Meneruskan data genre, penulis, dan penerbit ke view
        return view('buku.create', compact('genre', 'penulis', 'penerbit'));
    }

    public function store(Request $request)
    {
        // Validasi data yang diterima dari formulir
        $request->validate([
            'judul' => 'required|string|max:255',
            'sinopsis' => 'required|string',
            'tahun_penerbitan' => 'required|integer|min:1900',
            'genre_id' => 'required|exists:genre,id',
            'penulis_id' => 'required|exists:penulis,id',
            'penerbit_id' => 'required|exists:penerbit,id',
        ]);

        // Simpan data buku ke dalam database
        Buku::create($request->all());

        // Redirect pengguna ke halaman yang sesuai setelah berhasil menyimpan data
        return redirect()->route('buku.index')->with('success', 'Buku berhasil ditambahkan.');
    }


    public function show(Buku $buku)
    {
        return view('buku.show', compact('buku'));
    }

    public function edit(Buku $buku)
    {
        $genre = Genre::all(); // Mengambil semua genre dari database
        $penulis = Penulis::all(); // Mengambil semua penulis dari database
        $penerbit = Penerbit::all(); // Mengambil semua penerbit dari database

        return view('buku.edit', compact('buku', 'genre', 'penulis', 'penerbit'));
    }

    public function update(Request $request, Buku $buku)
    {
        $request->validate([
            'judul' => 'required|string|max:255',
            'sinopsis' => 'required|string',
            'tahun_penerbitan' => 'required|integer|min:1900',
            'genre_id' => 'required|exists:genre,id',
            'penulis_id' => 'required|exists:penulis,id',
            'penerbit_id' => 'required|exists:penerbit,id',
        ]);

        $buku->update($request->all());

        return redirect()->route('buku.index')->with('success', 'Buku berhasil diperbarui.');
    }

    public function destroy(Buku $buku)
    {
        $buku->delete();

        return redirect()->route('buku.index')->with('success', 'Buku berhasil dihapus.');
    }
}

ProjectReviewBuku/resources/views/buku/create.blade.php
@extends('layout.master')

@section('content')
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center">Tambah Buku</h2>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> Terdapat beberapa masalah dengan input Anda.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('buku.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="judul">Judul:</label>
                                <input type="text" class="form-control" id="judul" name="judul" required>
                            </div>
                            <div class="form-group">
                                <label for="sinopsis">Sinopsis:</label>
                                <textarea class="form-control" id="sinopsis" name="sinopsis" required></textarea>
                            </div>
                            <div class="form-group">
                                <label for="tahun_penerbitan">Tahun Penerbitan:</label>
                                <div class="input-group input-group-sm">
                                    <select name="tahun_penerbitan" id="tahun_penerbitan" class="custom-select">
                                        @for ($tahun = date('Y'); $tahun >= 201; $tahun--)
                                            <option value="{{ $tahun }}">{{ $tahun }}</option>
                                        @endfor
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="genre_id">Genre:</label><br>
                                @foreach ($genre as $item)
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="genre_id"
                                            id="genre_{{ $item->id }}" value="{{ $item->id }}">
                                        <label class="form-check-label"
                                            for="genre_{{ $item->id }}">{{ $item->nama }}</label>
                                    </div>
                                @endforeach
                            </div>
                            <div class="form-group">
                                <label>Penulis:</label><br>
                                @foreach ($penulis as $item)
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="penulis_id"
                                            id="penulis_{{ $item->id }}" value="{{ $item->id }}">
                                        <label class="form-check-label"
                                            for="penulis_{{ $item->id }}">{{ $item->nama }}</label>
                                    </div>
                                @endforeach
                            </div>
                            <div class="form-group">
                                <label>Penerbit:</label><br>
                                @foreach ($penerbit as $item)
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="penerbit_id"
                                            id="penerbit_{{ $item->id }}" value="{{ $item->id }}">
                                        <label class="form-check-label"
                                            for="penerbit_{{ $item->id }}">{{ $item->nama }}</label>
                                    </div>
                                @endforeach
                            </div>
                            <div class="text-center">
                                <div class="btn-group" role="group" aria-label="Button group">
                                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                                    <a class="btn btn-primary" href="{{ route('buku.index') }}">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

ProjectReviewBuku/resources/views/buku/edit.blade.php
@extends('layout.master')

@section('content')
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center">Edit Buku</h2> <!-- Perubahan judul card menjadi "Edit Buku" -->
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> Terdapat beberapa masalah dengan input Anda.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('buku.update', $buku->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="judul">Judul:</label>
                                <input type="text" class="form-control" id="judul" name="judul"
                                    value="{{ $buku->judul }}" required>
                            </div>
                            <div class="form-group">
                                <label for="sinopsis">Sinopsis:</label>
                                <textarea class="form-control" id="sinopsis" name="sinopsis" required>{{ $buku->sinopsis }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="tahun_penerbitan">Tahun Penerbitan:</label>
                                <div class="input-group input-group-sm">
                                    <select name="tahun_penerbitan" id="tahun_penerbitan" class="custom-select">
                                        @for ($tahun = date('Y'); $tahun >= 2017; $tahun--)
                                            <!-- Perbaikan pada loop tahun -->
                                            <option value="{{ $tahun }}"
                                                {{ $buku->tahun_penerbitan == $tahun ? 'selected' : '' }}>
                                                {{ $tahun }}</option>
                                        @endfor
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="genre_id">Genre:</label><br>
                                @foreach ($genre as $item)
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="genre_id"
                                            id="genre_{{ $item->id }}" value="{{ $item->id }}"
                                            {{ $buku->genre_id == $item->id ? 'checked' : '' }}>
                                        <!-- Perubahan untuk menandai radio button yang dipilih -->
                                        <label class="form-check-label"
                                            for="genre_{{ $item->id }}">{{ $item->nama }}</label>
                                    </div>
                                @endforeach
                            </div>
                            <div class="form-group">
                                <label>Penulis:</label><br>
                                @foreach ($penulis as $item)
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="penulis_id"
                                            id="penulis_{{ $item->id }}" value="{{ $item->id }}"
                                            {{ $buku->penulis_id == $item->id ? 'checked' : '' }}>
                                        <!-- Perubahan untuk menandai radio button yang dipilih -->
                                        <label class="form-check-label"
                                            for="penulis_{{ $item->id }}">{{ $item->nama }}</label>
                                    </div>
                                @endforeach
                            </div>
                            <div class="form-group">
                                <label>Penerbit:</label><br>
                                @foreach ($penerbit as $item)
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="penerbit_id"
                                            id="penerbit_{{ $item->id }}" value="{{ $item->id }}"
                                            {{ $buku->penerbit_id == $item->id ? 'checked' : '' }}>
                                        <!-- Perubahan untuk menandai radio button yang dipilih -->
                                        <label class="form-check-label"
                                            for="penerbit_{{ $item->id }}">{{ $item->nama }}</label>
                                    </div>
                                @endforeach
                            </div>
                            <div class="text-center">
                                <div class="btn-group" role="group" aria-label="Button group">
                                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                                    <a class="btn btn-primary" href="{{ route('buku.index') }}">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

ProjectReviewBuku/resources/views/buku/index.blade.php
@extends('layout.master')

@section('content')
    <div class="container-fluid"> <!-- Container-fluid untuk mengisi seluruh lebar halaman -->
        <div class="row justify-content-center"> <!-- Row justify-content-center untuk mengatur posisi ke tengah -->
            <div class="col-md-10"> <!-- Mengurangi lebar konten agar tidak terlalu lebar -->
                <h2 class="text-center mb-4">Daftar Buku</h2>
                <a href="{{ route('buku.create') }}" class="btn btn-success mb-3">Tambah Buku</a>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Judul</th>
                                <th class="text-center">Sinopsis</th>
                                <th class="text-center">Tahun Penerbitan</th>
                                <th class="text-center">Genre</th>
                                <th class="text-center" width="280px">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($buku as $key => $value)
                                <tr>
                                    <td class="text-center">{{ $key + 1 }}</td>
                                    <td class="text-center">{{ $value->judul }}</td>
                                    <td class="text-center">{{ $value->sinopsis }}</td>
                                    <td class="text-center">{{ $value->tahun_penerbitan }}</td>
                                    <td class="text-center">{{ $value->genre->nama }}</td>
                                    <!-- Mengambil deskripsi genre -->
                                    <td class="text-center">
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a class="btn btn-info btn-sm"
                                                href="{{ route('buku.show', $value->id) }}">Show</a>
                                            <a class="btn btn-primary btn-sm"
                                                href="{{ route('buku.edit', $value->id) }}">Edit</a>
                                            <form action="{{ route('buku.destroy', $value->id) }}" method="POST"
                                                style="display:inline;">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8" class="text-center">Daftar buku tidak tersedia</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

ProjectReviewBuku/resources/views/buku/show.blade.php
@extends('layout.master')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center mb-4">Detail Buku</h2>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <tbody>
                                    <tr>
                                        <th class="text-center" style="width: 20%;">Judul</th>
                                        <td>{{ $buku->judul }}</td>
                                    </tr>
                                    <tr>
                                        <th class="text-center">Sinopsis</th>
                                        <td>{{ $buku->sinopsis }}</td>
                                    </tr>
                                    <tr>
                                        <th class="text-center">Tahun Penerbitan</th>
                                        <td>{{ $buku->tahun_penerbitan }}</td>
                                    </tr>
                                    <tr>
                                        <th class="text-center">Genre</th>
                                        <td>{{ $buku->genre->nama }}</td>
                                    </tr>
                                    <tr>
                                        <th class="text-center">Deskripsi Genre</th>
                                        <td>{{ $buku->genre->deskripsi }}</td>
                                    </tr>
                                    <tr>
                                        <th class="text-center">Penulis</th>
                                        <td>{{ $buku->penulis->nama }}</td>
                                    </tr>
                                    <tr>
                                        <th class="text-center">Penerbit</th>
                                        <td>{{ $buku->penerbit->nama }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="text-center">
                            <a class="btn btn-primary mt-3" href="{{ route('buku.index') }}">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection